[cisco_ios]
AAB-CORE-R1 ansible_host=10.10.0.1
AAB-CORE-SW10 ansible_host=10.1.21.10
AAB-CORE-R2 ansible_host=10.10.0.5
AAH-R2 ansible_host=10.10.0.6
KBH-R2 ansible_host=10.20.0.6
ODE-R2 ansible_host=10.30.0.6
AAH-R1 ansible_host=10.10.0.2
KBH-R1 ansible_host=10.20.0.2
ODE-R1 ansible_host=10.30.0.2

[cisco_ios:vars]
ansible_connection=ansible.netcommon.network_cli
ansible_network_os=cisco.ios.ios
ansible_command_timeout=90
